---
- name: Create VPC
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ vpc_region }}"
    state: present
  register: vpc

- name: Store vpc id as environment variable
  set_fact:
    vpc_id: "{{ vpc.vpc.id }}"

- name: Create Public Subnet
  ec2_vpc_subnet:
    vpc_id : "{{ vpc_id }}"
    cidr: "{{ public_subnet_cidr }}"
    region: "{{ vpc_region }}"
    az: "{{ vpc_region }}a"
    state: present
    resource_tags:
      Name: "Public Subnet"
  register: public_subnet

- name: Store public subnet ID as environment variable
  set_fact:
    public_subnet_id: "{{ public_subnet.subnet.id }}"

- name: Create an Internet Gateway for VPC
  ec2_vpc_igw:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    state: present
  register: vpc_igw

- name: Store Internet Gateway ID as environment variable
  set_fact:
    igw_id: "{{ vpc_igw.gateway_id }}"

- name: Set Public Subnet Route -  Attach Internet Gateway
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    subnets:
      - "{{ public_subnet_id }}"
    tags:
      Name: "Public Subnet Route through Internet Gateway"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ igw_id }}"

- name: Create a Private Subnet
  ec2_vpc_subnet:
    vpc_id: "{{ vpc_id }}"
    cidr: "{{ private_subnet_cidr }}"
    region: "{{ vpc_region }}"
    az: "{{ vpc_region }}a"
    state: present
    resource_tags:
      Name: "Private Subnet"
  register: private_subnet

- name: Store Private Subnet ID into environment variable
  set_fact:
    private_subnet_id: "{{ private_subnet.subnet.id }}"

- name: Create an EIP for NAT Gateway
  ec2_eip:
    region: "{{ vpc_region }}"
    state: present
  register: eip

- name: Create NAT Gateway for Private Subnet
  ec2_vpc_nat_gateway:
    subnet_id: "{{ private_subnet_id }}"
    state: present
    wait: yes
    region: "{{ vpc_region }}"
    eip_address: "{{ eip.public_ip }}"
  register: nat_gateway

- name: Store NAT Gateway ID into an environment variable
  set_fact:
    nat_gateway_id: "{{ nat_gateway.nat_gateway_id }}"

- name: Set Private SUbnet Route - Attach NAT Gateway
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    subnets:
      - "{{ private_subnet_id }}"
    tags:
      Name: "Private Subnet Route through NAT Gateway"
    routes:
      - dest: "0.0.0.0/0"
        gateway_id: "{{ nat_gateway_id }}"

- name: Create a Default Security Group Allowing SSH
  ec2_group:
    name: "Default External"
    description: "Allow SSH, HTTP and ICMP"
    vpc_id: "{{ vpc_id }}"
    region: "{{ vpc_region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: ICMP
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0